### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by peterhorsley** [faxedhead/filesync#1]
v1.0.10 - seems like the libgit2sharp dll was not weaved into the filsync.exe portable exe during build?

Application: FileSync.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods+LibraryLifetimeObject..ctor()
   at LibGit2Sharp.Core.NativeMethods..cctor()

Exception Info: System.TypeInitializationException
   at LibGit2Sharp.Core.Proxy.git_repository_open_ext(System.String, LibGit2Sharp.Core.RepositoryOpenFlags, System.String)
   at LibGit2Sharp.Repository.IsValid(System.String)
   at FileSync.ViewModel.SyncViewModel.GetGitInfo(System.String)
   at FileSync.ViewModel.SyncViewModel.OnGitInfoTimer(System.Object)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()

**Comment by peterhorsley** [comment]
Fixed in v1.0.11 using same approach as https://github.com/icedream/citizenmp-server-updater/commit/e0e9fd5287c4c8697d56a694fa1511660c5bbc9f?diff=unified
